noun1 = input("A noun:")
noun2 = input("A noun:")
verb1 = input("A verb:")
verb2 = input("A verb:")
adjective1 = input("An adjective:")
adjective2 = input ("An adjective:")
adjective3 = input("An adjective:")
adjective4 = input("An adjective:")

print(f"Yesterday I went to {noun1} to {verb1}")
print(f"There was a {adjective1} crowd")
print(f"I met with {noun2}, she was {adjective2}")
print(f"Then i did {verb2} to home")
print(f"It was a {adjective3} day")
print(f"I was {adjective4}")
